### PR TITLE
Switch from bacon to rspec

### PR DESCRIPTION
**Pull request by segiddins**
Thoughts?

### CODE REVIEW

**Comment by kylef** [comment]
What's the justification for this?

**Comment by segiddins** [comment]
I prefer rspec, particularly its mocking capabilities, and it makes the project more welcoming to others since RSpec is certainly more common than bacon. We discussed this with regards to CocoaPods a while back and decided we'd like to switch (abstractly, since switching obviously takes time).

**Comment by segiddins** [comment]
rspec also has much more useful output when things fail

**Comment by floere** [comment]
@segiddins Even though I like Bacon for its simplicity, I very much agree with your points :+1:

**Comment by manuyavuz** [comment]
I wonder why rspec was not the initial choice. Was there a special reasoning, other than thing like developers' familiarity to bacon?

**Comment by segiddins** [comment]
@floere I like its simplicity as well, but I also find it hampering at times, and RSpec's feature set these days is so great it far outweighs the additional complexity imho.

**Comment by floere** [comment]
@manuyavuz Initially, especially in Trunk (but also search), we tended towards including few dependencies, and if so, the smallest possible that work for us. Bacon fit that well. (@alloy has had a large influence on this decision as well, iirc)

**Comment by floere** [comment]
@segiddins I agree with you. I tend to have trouble remembering its `expect().to be < …` syntax, as it does not seem that intuitive to me, but that's perhaps just me.

**Comment by segiddins** [comment]
:shipit: !

**Pull request merged**
