### PR TITLE
Add a failing test case for swapping children with dependencies of same name

### PR DESCRIPTION
**Pull request by maxvt**
See discussion in https://github.com/CocoaPods/Molinillo/issues/46

### CODE REVIEW

**Comment by segiddins** [comment]
Thanks so much!

**Comment by segiddins** [comment]
This doesn't merge cleanly

**Comment by maxvt** [comment]
@segiddins, how about now? The test is failing on some submodule error, I do not know if that is expected and how to resolve it if it's not what should be happening. There's a separate PR on the submodule repo as well: https://github.com/CocoaPods/Resolver-Integration-Specs/pull/5

**Comment by greysteil** [comment]
Swapping has been removed a while back - I don't think this is relevant anymore.

**Pull request closed without merging**
