### PR TITLE
Document all the things

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by alloy** [comment]
Nice :+1: 

You know what would be really handy, I think, a few simple example scripts that use it:

1. The traditional lib dependency with version resolution.
2. Something completely unrelated to libraries and software versions. I don’t have an example right now, but something like that would show non-dependency manager folk to how they can use Molinillo too.

**Comment by segiddins** [comment]
@alloy pull requests welcome 🙈

**Comment by alloy** [comment]
Booyakasha, rudeboi! :stuck_out_tongue_winking_eye: 

Seriously, though, do you have ideas for example number 2?

**Comment by segiddins** [comment]
Not really? This is complete overkill for anything that can be done with a simple topological sort, and those are the only other dependency resolution problems that come to mind.

**Comment by alloy** [comment]
Hmm, the point wasn’t so much to give a great real-world example, but more to show how to use the API, so it can be silly.

**Comment by orta** [comment]
pokemon evolution dependency graphs

**Pull request merged**
