### PR TITLE
Make richer version conflict messages possible

### PR DESCRIPTION
**Pull request by segiddins**
\c @indirect

### CODE REVIEW

**Comment by indirect** [comment]
:+1:

**Comment by alloy** [comment]
Nice :+1:

**Comment by segiddins** [comment]
I'm kinda tempted to use this and make the tree-style output Bundler uses a builtin method on `VersionConflict`, something like `tree_message`. How does that sound?

**Comment by indirect** [comment]
I'm for it, but I designed the Bundler output. :sweat_smile:

**Comment by alloy** [comment]
Just to be clear we’re on the same page, can you provide examples of the output?

**Comment by segiddins** [comment]
```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    jquery-rails, resolved to 4.0.4 depends on
      railties (>= 4.2.0)

    rails-i18n, resolved to 4.0.4 depends on
      railties (~> 5.0)

    rails, resolved to 5.0.0.alpha depends on
      railties (= 5.0.0.alpha)

    codemirror-rails (= 4.2), resolved to 4.2 depends on
      railties (< 5, >= 3.0)

    rspec-rails (~> 2.14.0), resolved to 2.14.2 depends on
      railties (>= 3.0)

Could not find gem 'railties (~> 5.0)', which is required by gem 'jquery-rails', in any of the sources.
```

**Comment by segiddins** [comment]
(The code that generates that is pretty much https://github.com/bundler/bundler/blob/master/lib/bundler/resolver.rb#L13-L68)

**Comment by alloy** [comment]
Ok cool, yeah I like this message :+1:

I’m less a fan of repeating the name of the dependency (`railties`) over and over, but maybe there’s a reason for that?

**Comment by segiddins** [comment]
@alloy reason for the repeated name is specific to this example, where lots of things had dependencies on `railties`. Note, I'm not suggesting making this format the default (because it requires a few parameters from the user), but I do think building it in would be nice.

**Comment by alloy** [comment]
Gotcha. I think it’s a good idea, do it :+1:

**Pull request merged**
