### PR TITLE
Lazily load set

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It helps bundler supporting `set` as a default gem.

### CODE REVIEW

**Review by segiddins — COMMENTED** [review]
given https://bugs.ruby-lang.org/issues/5653, i feel like Autoload should not be used.

**Comment by deivid-rodriguez** [comment]
That proposal was widthdrawn by Matz two years ago, see the last messages. I think it's a good call since most of the ecosystem relies on `autoload` for lazily loading things (see for example the brand new rails code, `zeitwerk`), and the thread safety issues were fixed.

That said if you prefer to use inline requires I don't mind changing this.

**Comment by segiddins** [comment]
I think I prefer inline requires

**Comment by deivid-rodriguez** [comment]
Updated to use inline requires! :+1:

**Comment by deivid-rodriguez** [comment]
Three hours and still no feedback from TravisCI. @segiddins is it ok if I propose a PR to move to Github Actions?

**Review by segiddins — APPROVED** [review]

**Comment by segiddins** [comment]
@deivid-rodriguez that would be great!

**Comment by deivid-rodriguez** [comment]
Turns out `ruby/setup-ruby` doesn't support ruby 2.0.0. Is it ok to drop support for that? If it is, and since 2.1 and 2.2 are not even tested on the current CI and reached their end of life too a while ago, is is ok to drop support for those too?

**Comment by segiddins** [comment]
@deivid-rodriguez going 2.3+ should be fine

**Comment by deivid-rodriguez** [comment]
Great, I created #152!

**Pull request merged**
