### PR TITLE
[Resolution] Delete outdated requirements

### LINKED ISSUE #48: Regression in 0.5.2
See https://travis-ci.org/CocoaPods/CocoaPods/builds/170029689

### PR DESCRIPTION
**Pull request by segiddins**
Closes #48 

- [x] CHANGELOG
- [x] Spec

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
Uh. Whoops. I approve. :P

**Comment by segiddins** [comment]
@indirect please re-review, I re-wrote the patch

**Comment by indirect** [comment]
looks good! @homu r+

**Pull request merged**
