### PR TITLE
[Resolution] Keep a stack of requirement parents

### PR DESCRIPTION
**Pull request by segiddins**
See https://github.com/bundler/bundler/issues/5425 & the tests for the issue this fixes

Depends upon https://github.com/CocoaPods/Resolver-Integration-Specs/pull/9

### CODE REVIEW

**Comment by indirect** [comment]
LGTM, nice work figuring this out 👍

**Comment by segiddins** [comment]
Uh oh, it appears fixing the specs has uncovered an issue with the resolver :(

**Comment by segiddins** [comment]
This should be green now.  @indirect r?

**Comment by indirect** [comment]
Nice. r+

**Pull request merged**
